# Generated by Django 3.0.7 on 2020-06-13 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200613_1857'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmarketprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market', to='products.Product'),
        ),
    ]
