# Generated by Django 3.0.7 on 2020-07-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('market', '0002_auto_20200613_1857'),
    ]

    operations = [migrations.RemoveField(
        model_name='productmarketprice',
        name='close_time',
    ),
        migrations.RemoveField(
            model_name='productmarketprice',
            name='open_time',
        ),
        migrations.AddField(
            model_name='productmarketprice',
            name='close_time',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmarketprice',
            name='open_time',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
