build-and-deploy:
  image: node:8.16.2
  stage: build
  before_script:
    # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - git config --global user.email "runner@gitlab.com"
    - git config --global user.name "Gitlab Runner"
    - git checkout -b ci_processing
  script:
    - npm install
    - npm run build
    - printf "$CI_COMMIT_REF_NAME\n$CI_COMMIT_SHORT_SHA\n" > .version.txt
    - printf "$CI_PROJECT_URL/commit/$CI_COMMIT_SHA\n" >> .version.txt
    - git add .version.txt -f
    - git add build/static/dashboard/index.js -f
    - git add webpack-stats.json -f
    - git commit -m "Added dashboard statics"
    - git remote add piku $PAAS_HOST
    - ssh piku@$HOST stop dashboard
    - git push piku ci_processing --force
    - ssh piku@$HOST restart dashboard
  only:
    - master
