# Generated by Django 3.0.7 on 2020-06-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'ordering': ['-pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sell_price', models.DecimalField(decimal_places=4, max_digits=32)),
                ('sell_volume', models.BigIntegerField()),
                ('sell_orders', models.BigIntegerField()),
                ('buy_price', models.DecimalField(decimal_places=4, max_digits=32)),
                ('buy_volume', models.BigIntegerField()),
                ('buy_orders', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
